#!/usr/bin/env bash

# Exit at any error
set -e

# Make sure FreeSurfer is sourced
[ ! -e "$FREESURFER_HOME" ] && echo "error: freesurfer has not been properly sourced" && exit 1

# If requesting help
if  [ $# == 1 ] && [  $1 == "--help" ]
then
  echo " "
  echo "Bayesian segmentation with histological whole brain atlas."
  echo " "
  echo "Next-Generation histological atlas for high-resolution segmentation of human brain MRI"
  echo "Casamitjana et al. (in preparation)"
  echo " "
  echo "Usage:"
  echo "   segment.sh INPUT_SCAN OUTPUT_DIRECTORY GPU THREADS [BF_MODE] [GMM_MODE]"
  echo " "
  echo "INPUT SCAN: scan to process, in mgz or nii(.gz) format"
  echo "OUTPUT_DIRECTORY: directory with segmentations, volume files, etc"
  echo "GPU: set to 1 to use the GPU (*highly* recommended but requires a 24GB GPU!)"
  echo "THREADS: number of CPU threads to use (use -1 for all available threads)"
  echo "BF_MODE (optional): bias field model: dct (default), polynomial, or hybrid"
  echo "GMM_MODE (optional): must be 1mm (default) unless you define your own (see documentation)"
  echo " "
  exit 0
fi

# Find path to shell script
SCRIPTPATH="$FREESURFER_HOME_FSPYTHON/python/packages/3D_photo_recon/scripts/recon_case.py"

# Try to find atlas data
MODELPATH="$FREESURFER_HOME/models/photo_imputation_unet.pth"

if [ ! -f "$MODELPATH" ];
then
  echo " "
  echo "   Model file not found. Please download atlas from: "
  echo "       https://ftp.nmr.mgh.harvard.edu/pub/dist/lcnpublic/dist/dissection_photo_model/photo_imputation_unet.pth"
  echo "   and copy it to:  "
  echo "      $MODELPATH "
  echo "   You only need to do this once. You can use the following commands: "
  echo "      1: cd $FREESURFER_HOME/models"
  echo "      2a (in Linux): wget https://ftp.nmr.mgh.harvard.edu/pub/dist/lcnpublic/dist/dissection_photo_model/photo_imputation_unet.pth "
  echo "      2b (in MAC): curl -o atlas.zip https://ftp.nmr.mgh.harvard.edu/pub/dist/lcnpublic/dist/dissection_photo_model/photo_imputation_unet.pth "
  echo " "
  exit 1
fi

fspython $SCRIPTPATH $@

echo "  "
echo "*****************"
echo "* All done!!!!! *"
echo "*****************"
